services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=constrallianz
      - MONGO_INITDB_ROOT_PASSWORD=constrallianz
  
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: constrallianz
      ME_CONFIG_MONGODB_ADMINPASSWORD: constrallianz
      ME_CONFIG_MONGODB_URL: mongodb://constrallianz:constrallianz@mongodb:27017/constrallianz?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:
